# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02c1fb388022222da82bfa5688e3a1abaa41c4c3e607fbb0596006b0535c3fac4e24680b0688214fc169d319e2a0febd3130dcd7ec1e5ef5d307d701dd862de4

test:
  secret_key_base: d1f95624c2a3440b7b822cdeb32e569d11bde53c6fbed099ea64164f7ab7a9a3ed9422ed09ce90727c56fe33264b7cc0cd1b611fb90ff834e3aa501831bb54d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
